version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: customer_reviews_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customer_reviews
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - customer_reviews_network

volumes:
  mysql_data:
    driver: local

networks:
  customer_reviews_network:
    driver: bridge
